ScriptRunner/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from ScriptRunner import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.Home.as_view(), name="script_runner_home"),
    path('process_launcher/', include('process_launcher.urls'), name='process_launcher')

]

process_launcher/urls.py
from django.urls import path
from process_launcher import views

app_name = "process_launcher"

urlpatterns = [
    path('', views.HomeProcessLauncher.as_view(), name="pl_home_view"),
    path('script_params', views.script_request_handler, name="script_config")

]

process_launcher/models.py
from django.db import models

# Create your models here.

process_launcher/forms.py
from django import forms
from .script_handler import ScriptConfig


class ScriptSelectFrom(forms.Form):
    processes = forms.ChoiceField(widget=forms.Select, choices=ScriptConfig().get_script_choices())


class ScriptArgsForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.field_data = kwargs.pop("field_data")
        super().__init__(*args, **kwargs)

        for field in self.field_data:
            if field["type"] == "string":
                self.fields[field['name_to_show']] = forms.CharField(
                    max_length=100,
                    help_text="TBD",
                    required=True,
                    initial="default"
                )
            elif field["type"] == "date":
                self.fields[field['name_to_show']] = forms.DateField()

ScriptRunner/views.py
from django.views.generic import TemplateView


class Home(TemplateView):
    template_name = "ScriptRunner/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

process_launcher/views.py
import json
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView
from django.shortcuts import render
from django.urls import reverse
from process_launcher.forms import ScriptSelectFrom, ScriptArgsForm
from process_launcher.script_handler import ScriptConfig


class HomeProcessLauncher(TemplateView):
    template_name = "process_launcher/pl_base.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["script_select_form"] = ScriptSelectFrom()
        return context


def script_request_handler(request):
    if request.method == "GET":
        form = ScriptSelectFrom(request.GET)
        if form.is_valid():
            selected_script = form.cleaned_data['processes']
            config = ScriptConfig()
            script_args = config.get_args_of_script(selected_script)
            script_args_form = ScriptArgsForm(field_data=script_args)
            return render(request, "process_launcher/pl_base.html", context={"script_args_form": script_args_form})
    elif request.method == "POST":
        return HttpResponse(json.dumps("post data"), content_type="application/json")

ScriptRunner/templates/ScriptRunner/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Script Runner</title>
    <script type="text/javascript" src="{% static '/js/jquery.js' %}" ></script>
    <script type="text/javascript" src="{% static '/js/bootstrap.min.js' %}" ></script>

    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/ScriptRunner/css/styles.css' %}">

</head>
<body>
  <header>
    <nav id="header-nav" class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <a href="{% url 'script_runner_home' %}" class="pull-left visible-md visible-lg">
            <div id="logo-img"></div>
          </a>
          <div class="navbar-brand">
            <a href="{% url 'script_runner_home' %}"><h1>Script Runner Test Project</h1></a>
          </div>
        </div>
      </div>
    </nav>
  </header>
<form class="form-inline">
    <a id="runner_tab" href="{% url 'process_launcher:pl_home_view'%}">Process Launcher</a>
</form>

{% block content %}
{% endblock %}

{% block js %}
{% endblock js %}

</body>
</html>

process_launcher/templates/process_launcher/pl_base.html
{% extends 'ScriptRunner/index.html'%}
{% load static %}

{% block content %}

<h3>Welcome to the process launcher page</h3>


{% if  script_select_form %}
<form action="{% url 'process_launcher:script_config' %}" method="get" >
    {%csrf_token%}
    {{ script_select_form }}
     <input type="submit" value="Select" class="select-btn">
</form>
{% endif %}


{% if script_args_form %}
<form action="{% url 'process_launcher:script_config' %}" method="post" >
    {%csrf_token%}
    <table border="1">
    {{ script_args_form }}
    </table>
     <input type="submit" value="Select" class="select-btn">
</form>
{% endif %}

{% endblock %}


{% block js %}
    <script type="text/javascript" src="{% static 'process_launcher/js/ps.js' %}" ></script>
    <link rel="stylesheet" href="{% static '/process_launcher/css/pl_style.css' %}">
{% endblock js%}